CREATE TABLE `userauth` (
	`ID` VARCHAR(20) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',								--ID, useracc테이블 FK
	`AUTHORITY` VARCHAR(500) NOT NULL DEFAULT 'ROLE_USER' COLLATE 'utf8mb4_0900_ai_ci', --계정 권한
	INDEX `ID` (`ID`) USING BTREE,
	CONSTRAINT `FK_userauth_useracc` FOREIGN KEY (`ID`) REFERENCES `useracc` (`ID`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB